### ISSUE TITLE
Cannot use backend after install on EE2.2.4

### ISSUE THREAD

**Issue by vanpoppel** [mageplaza/magento-2-social-login#107]
### Preconditions
1. Magento: 2.2.4 (EE) with the admin nofication module disabled
2. PHP: 7.1
3. MySQL: 5.7
4. Socal Login: 2.6.1

### Steps to reproduce
1. Install Magento without the Magento AdminNotification module
2. Composer update mageplaza/magento-2-social-login
3. bin/magento setup:upgrade
4. bin/magento cache:flush (also remove static and generated content/code)
5. Open admin panel

### Expected result
1. The login form for the admin panel (if the table doesn't exist, don't use it)
2. Or a dependency on Magento/AdminNotification (defined in module.xml) which would result in not being able to install the module until the module you're depending on is installed.

### Actual result
1. White error page with a report number.
From the error log:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'accept.adminnotification_inbox' doesn't exist, query was: SELECT `adminnotification_inbox`.* FROM `adminnotification_inbox` WHERE (title = 'Preparing for the GDPR: Easy step to implement') AND (url = 'https:\/\/www.mageplaza.com\/magento-2-gdpr-extension\/?utm_source=notification&amp;utm_medium=rss&amp;utm_campaign=gdpr-m2')`

**Comment by gixid192** [comment]
This looks like problems from the Core extension, could you run the composer upgrade command instead?
Or maybe with `--with-dependencies` option to make sure the Core module is up to date.
You can open the composer.json in the Core module folder (vendor/mageplaza/module-core) and check the version key, it should be 1.3.12 now.

**Comment by vanpoppel** [comment]
The problem is caused because your core module tries to use the AdminNotification module, which we have disabled from the start. The tables for this module therefor doesn't exist, and your core module will present an error.

I have updated the issue with the first step to reproduce.

**Comment by gixid192** [comment]
Thanks for your report, we will check and fix this issue soon.

**Comment by gixid192** [comment]
@vanpoppel The problem has been fixed in the new version.
Kindly help us check it once again. Thank you.

**Comment by andrei-vdc** [comment]
this is still an issue in magento ee 2.4.3-p1. with Magento_AdminNotification disabled we get the same issue
