### ISSUE TITLE
Social Login Plugin Override Page Title

### ISSUE THREAD

**Issue by ashishshah-github** [mageplaza/magento-2-social-login#37]
### Preconditions

1. Magento: 2.1.5
2. PHP: 7.0.10
3. MySQL: 5.7.14

we have installed extension but it is overriding Page Title of default contact us page. it is showing "Create New Customer Account" Page title on Contact Us Page.

So can you please look on to this issue ?

Thanks!

**Comment by haitv282** [comment]
Hi there,

We have fixed this issue on the latest version 2.3.5. Please upgrade extension to solve it.

**Comment by bnchdrff** [comment]
what commit fixed this issue? it's still happening for me with code from `master`

**Comment by walaoehh** [comment]
@bnchdrff do you find any solution to this issue? I am having this too

**Comment by MaxxLuong** [comment]
@walaoehh 
It looked to me that you are using an old version of our extension. Please pull the latest code(Social Login V2.4.0) to fix the current issue.If the problem still exists.Please submit a ticket to [https://mageplaza.freshdesk.com/ ](https://mageplaza.freshdesk.com/) our technical team will look into this.

**Comment by walaoehh** [comment]
@MaxxLuong thanks for the update. issue fixed. thumbs up 👍
